In [2]:
# Example 4-1. Declaring a vector in Python using a list 
 
v = [3, 2]
print(v)


[3, 2]


In [3]:
# Example 4-2. Declaring a vector in Python using NumPy 
import numpy as np

v = np.array([3, 2])
print(v)


[3 2]


In [4]:
# Example 4-3. Declaring a three-dimensional vector in Python using NumPy 
import numpy as np
v = np.array([4, 1, 2])
print(v)

[4 1 2]


In [5]:
# Example 4-4. Declaring a five-dimensional vector in Python using NumPy 
import numpy as np
v = np.array([6, 1, 5, 8, 3])
print(v)

[6 1 5 8 3]


In [6]:
# Example 4-5. Adding two vectors in Python using NumPy 
from numpy import array

v = array([3,2])
w = array([2,-1])

# sum the vectors
v_plus_w = v + w

# display summed vector
print(v_plus_w) # [5, 1]

[5 1]


In [7]:
# Example 4-6. Scaling a number in Python using NumPy 

from numpy import array

v = array([3,1])

# scale the vector
scaled_v = 2.0 * v

# display scaled vector
print(scaled_v) # [6 2]

[6. 2.]


In [8]:
# Example 4-7. Matrix vector multiplication in NumPy 
from numpy import array

# compose basis matrix with i-hat and j-hat
basis = array(
    [[3, 0],
     [0, 2]]
 )

# declare vector v
v = array([1,1])

# create new vector
# by transforming v with dot product
new_v = basis.dot(v)

print(new_v) # [3, 2]

[3 2]


In [9]:
# Example 4-8. Separating the basis vectors and applying them as a transformation 
from numpy import array

# Declare i-hat and j-hat
i_hat = array([2, 0])
j_hat = array([0, 3])

# compose basis matrix using i-hat and j-hat
# also need to transpose rows into columns
basis = array([i_hat, j_hat]).transpose()

# declare vector v
v = array([1,1])

# create new vector
# by transforming v with dot product
new_v = basis.dot(v)

print(new_v) # [2, 3]

[2 3]


In [10]:
# Example 4-9. Transforming a vector using NumPy 
from numpy import array

# Declare i-hat and j-hat
i_hat = array([2, 0])
j_hat = array([0, 3])

# compose basis matrix using i-hat and j-hat
# also need to transpose rows into columns
basis = array([i_hat, j_hat]).transpose()


# declare vector v 0
v = array([2,1])

# create new vector
# by transforming v with dot product
new_v = basis.dot(v)

print(new_v) # [4, 3]

[4 3]


In [11]:
# Example 4-10. A more complicated transformation 
from numpy import array

# Declare i-hat and j-hat
i_hat = array([2, 3])
j_hat = array([2, -1])

# compose basis matrix using i-hat and j-hat
# also need to transpose rows into columns
basis = array([i_hat, j_hat]).transpose()

# declare vector v 0
v = array([2,1])

# create new vector
# by transforming v with dot product
new_v = basis.dot(v)

print(new_v) # [6, 5]

[6 5]


In [14]:
# Example 4-11. Combining two transformations 
from numpy import array

# Transformation 1
i_hat1 = array([0, 1])
j_hat1 = array([-1, 0])
transform1 = array([i_hat1, j_hat1]).transpose()

# Transformation 2
i_hat2 = array([1, 0])
j_hat2 = array([1, 1])

transform2 = array([i_hat2, j_hat2]).transpose()

# Combine Transformations
combined = transform2 @ transform1

# Test
print("COMBINED MATRIX:\n {}".format(combined))

v = array([1, 2])
print(combined.dot(v))  # [-1, 1]



COMBINED MATRIX:
 [[ 1 -1]
 [ 1  0]]
[-1  1]


In [16]:
# Example 4-12. Applying the transformations in reverse 
from numpy import array

# Transformation 1
i_hat1 = array([0, 1])
j_hat1 = array([-1, 0])
transform1 = array([i_hat1, j_hat1]).transpose()

# Transformation 2
i_hat2 = array([1, 0])
j_hat2 = array([1, 1])
transform2 = array([i_hat2, j_hat2]).transpose()

# Combine Transformations, apply sheer first and then rotation
combined = transform1 @ transform2

# Test
print("COMBINED MATRIX:\n {}".format(combined))

v = array([1, 2])
print(combined.dot(v)) # [-2, 3]

COMBINED MATRIX:
 [[ 0 -1]
 [ 1  1]]
[-2  3]


## Determinants