In [2]:
# Example 4-1. Declaring a vector in Python using a list 
 
v = [3, 2]
print(v)


[3, 2]


In [3]:
# Example 4-2. Declaring a vector in Python using NumPy 
import numpy as np

v = np.array([3, 2])
print(v)


[3 2]


In [4]:
# Example 4-3. Declaring a three-dimensional vector in Python using NumPy 
import numpy as np
v = np.array([4, 1, 2])
print(v)

[4 1 2]


In [5]:
# Example 4-4. Declaring a five-dimensional vector in Python using NumPy 
import numpy as np
v = np.array([6, 1, 5, 8, 3])
print(v)

[6 1 5 8 3]


In [6]:
# Example 4-5. Adding two vectors in Python using NumPy 
from numpy import array

v = array([3,2])
w = array([2,-1])

# sum the vectors
v_plus_w = v + w

# display summed vector
print(v_plus_w) # [5, 1]

[5 1]


In [7]:
# Example 4-6. Scaling a number in Python using NumPy 

from numpy import array

v = array([3,1])

# scale the vector
scaled_v = 2.0 * v

# display scaled vector
print(scaled_v) # [6 2]

[6. 2.]


In [8]:
# Example 4-7. Matrix vector multiplication in NumPy 
from numpy import array

# compose basis matrix with i-hat and j-hat
basis = array(
    [[3, 0],
     [0, 2]]
 )

# declare vector v
v = array([1,1])

# create new vector
# by transforming v with dot product
new_v = basis.dot(v)

print(new_v) # [3, 2]

[3 2]


In [9]:
# Example 4-8. Separating the basis vectors and applying them as a transformation 
from numpy import array

# Declare i-hat and j-hat
i_hat = array([2, 0])
j_hat = array([0, 3])

# compose basis matrix using i-hat and j-hat
# also need to transpose rows into columns
basis = array([i_hat, j_hat]).transpose()

# declare vector v
v = array([1,1])

# create new vector
# by transforming v with dot product
new_v = basis.dot(v)

print(new_v) # [2, 3]

[2 3]


In [10]:
# Example 4-9. Transforming a vector using NumPy 
from numpy import array

# Declare i-hat and j-hat
i_hat = array([2, 0])
j_hat = array([0, 3])

# compose basis matrix using i-hat and j-hat
# also need to transpose rows into columns
basis = array([i_hat, j_hat]).transpose()


# declare vector v 0
v = array([2,1])

# create new vector
# by transforming v with dot product
new_v = basis.dot(v)

print(new_v) # [4, 3]

[4 3]


In [11]:
# Example 4-10. A more complicated transformation 
from numpy import array

# Declare i-hat and j-hat
i_hat = array([2, 3])
j_hat = array([2, -1])

# compose basis matrix using i-hat and j-hat
# also need to transpose rows into columns
basis = array([i_hat, j_hat]).transpose()

# declare vector v 0
v = array([2,1])

# create new vector
# by transforming v with dot product
new_v = basis.dot(v)

print(new_v) # [6, 5]

[6 5]


In [14]:
# Example 4-11. Combining two transformations 
from numpy import array

# Transformation 1
i_hat1 = array([0, 1])
j_hat1 = array([-1, 0])
transform1 = array([i_hat1, j_hat1]).transpose()

# Transformation 2
i_hat2 = array([1, 0])
j_hat2 = array([1, 1])

transform2 = array([i_hat2, j_hat2]).transpose()

# Combine Transformations
combined = transform2 @ transform1

# Test
print("COMBINED MATRIX:\n {}".format(combined))

v = array([1, 2])
print(combined.dot(v))  # [-1, 1]



COMBINED MATRIX:
 [[ 1 -1]
 [ 1  0]]
[-1  1]


In [16]:
# Example 4-12. Applying the transformations in reverse 
from numpy import array

# Transformation 1
i_hat1 = array([0, 1])
j_hat1 = array([-1, 0])
transform1 = array([i_hat1, j_hat1]).transpose()

# Transformation 2
i_hat2 = array([1, 0])
j_hat2 = array([1, 1])
transform2 = array([i_hat2, j_hat2]).transpose()

# Combine Transformations, apply sheer first and then rotation
combined = transform1 @ transform2

# Test
print("COMBINED MATRIX:\n {}".format(combined))

v = array([1, 2])
print(combined.dot(v)) # [-2, 3]

COMBINED MATRIX:
 [[ 0 -1]
 [ 1  1]]
[-2  3]


## Determinants

Testing for a 0 determinant is highly helpful to determine if a transformation has linear dependence. When you encounter this you will likely find a difficult or unsolvable problem on your hands. Matrixes with 0 determinant are ones on a single number line no matter the number of dimensions.


In [4]:
# Example 4-13. Calculating a determinant 
from numpy.linalg import det
from numpy import array

i_hat = array([3, 0])
j_hat = array([0, 2])

basis = array([i_hat, j_hat]).transpose()

print('Basis:\n',basis)

determinant = det(basis)
print('\nDeterminant:', determinant) # prints 6.0


Basis:
 [[3 0]
 [0 2]]

Determinant: 6.0


In [5]:
# Example 4-14. A determinant for a shear 
from numpy.linalg import det
from numpy import array

i_hat = array([1, 0])
j_hat = array([1, 1])

basis = array([i_hat, j_hat]).transpose()

print('Basis:\n',basis)

determinant = det(basis)

print('\nDeterminant:', determinant)  # prints 1.0

Basis:
 [[1 1]
 [0 1]]

Determinant: 1.0


In [7]:
# Example 4-15. A negative determinant 
from numpy.linalg import det
from numpy import array

i_hat = array([-2, 1])
j_hat = array([1, 2])

basis = array([i_hat, j_hat]).transpose()

print('Basis:\n',basis)

determinant = det(basis)

print('\nDeterminant:', determinant) # prints -5.0

Basis:
 [[-2  1]
 [ 1  2]]

Determinant: -5.000000000000001


In [9]:
# Example 4-16. A determinant of zero 
from numpy.linalg import det
from numpy import array

i_hat = array([-2, 1])
j_hat = array([3, -1.5])

basis = array([i_hat, j_hat]).transpose()

print('Basis:\n',basis)

determinant = det(basis)

print('\nDeterminant:', determinant) # prints 0.0

Basis:
 [[-2.   3. ]
 [ 1.  -1.5]]

Determinant: 0.0


## Linear Equations

In [11]:
# Example 4-17. Using SymPy to study the inverse and identity matrix 
from sympy import *

# 4x + 2y + 4z = 44
# 5x + 3y + 7z = 56
# 9x + 3y + 6z = 72

A = Matrix([
    [4, 2, 4],
    [5, 3, 7],
    [9, 3, 6]
])

# dot product between A and its inverse
# will produce identity function
inverse = A.inv()
identity = inverse * A

# prints Matrix([[-1/2, 0, 1/3], [11/2, -2, -4/3], [-2, 1, 1/3]])
print("INVERSE:\n {}".format(inverse))

# prints Matrix([[1, 0, 0], [0, 1, 0], [0, 0, 1]])
print("\nIDENTITY:\n {}".format(identity))

INVERSE:
 Matrix([[-1/2, 0, 1/3], [11/2, -2, -4/3], [-2, 1, 1/3]])

IDENTITY:
 Matrix([[1, 0, 0], [0, 1, 0], [0, 0, 1]])


In [13]:
# Example 4-18. Using NumPy to solve a system of equations 
from numpy import array
from numpy.linalg import inv

# 4x + 2y + 4z = 44
# 5x + 3y + 7z = 56
# 9x + 3y + 6z = 72

A = array([
    [4, 2, 4],
    [5, 3, 7],
    [9, 3, 6]
])

B = array([
    44,
    56,
    72
])

X = inv(A).dot(B)

print(X) # [ 2. 34. -8.] So x = 2, y = 34, and z = –8. 


[ 2. 34. -8.]


In [14]:
# Example 4-19. Using SymPy to solve a system of equations 
from sympy import *

# 4x + 2y + 4z = 44
# 5x + 3y + 7z = 56
# 9x + 3y + 6z = 72

A = Matrix([
    [4, 2, 4],
    [5, 3, 7],
    [9, 3, 6]
])

B = Matrix([
    44,
    56,
    72
])

X = A.inv() * B

print(X) # Matrix([[2], [34], [-8]]) So x = 2, y = 34, and z = –8. 

Matrix([[2], [34], [-8]])


## Eigenvectors and Eigenvalues
Matrix decomposition: 

    eigendecomposition


In [16]:
# Example 4-20. Performing eigendecomposition in NumPy 
from numpy import array, diag
from numpy.linalg import eig, inv

A = array([
    [1, 2],
    [4, 5]
])

eigenvals, eigenvecs = eig(A)

print("EIGENVALUES")
print(eigenvals)
print("\nEIGENVECTORS")
print(eigenvecs)

"""
EIGENVALUES
[-0.46410162  6.46410162]

EIGENVECTORS
[[-0.80689822 -0.34372377]
[ 0.59069049 -0.9390708 ]]
"""


EIGENVALUES
[-0.46410162  6.46410162]

EIGENVECTORS
[[-0.80689822 -0.34372377]
 [ 0.59069049 -0.9390708 ]]


'\nEIGENVALUES\n[-0.46410162  6.46410162]\n\nEIGENVECTORS\n[[-0.80689822 -0.34372377]\n[ 0.59069049 -0.9390708 ]]\n'

In [17]:
# Example 4-21. Decomposing and recomposing a matrix in NumPy 
from numpy import array, diag
from numpy.linalg import eig, inv

A = array([
    [1, 2],
    [4, 5]
])

eigenvals, eigenvecs = eig(A)

print("EIGENVALUES")
print(eigenvals)
print("\nEIGENVECTORS")
print(eigenvecs)

print("\nREBUILD MATRIX")
Q = eigenvecs
R = inv(Q)

L = diag(eigenvals)
B = Q @ L @ R

print(B)

"""
EIGENVALUES
[-0.46410162  6.46410162]

EIGENVECTORS
[[-0.80689822 -0.34372377]
 [ 0.59069049 -0.9390708 ]]

REBUILD MATRIX
[[1. 2.]
 [4. 5.]]
"""

EIGENVALUES
[-0.46410162  6.46410162]

EIGENVECTORS
[[-0.80689822 -0.34372377]
 [ 0.59069049 -0.9390708 ]]

REBUILD MATRIX
[[1. 2.]
 [4. 5.]]


'\nEIGENVALUES\n[-0.46410162  6.46410162]\n\nEIGENVECTORS\n[[-0.80689822 -0.34372377]\n [ 0.59069049 -0.9390708 ]]\n\nREBUILD MATRIX\n[[1. 2.]\n [4. 5.]]\n'

# Exercises 

1. Vector $\vec{v}$ has a value of [1, 2] but then a transformation happens. $\hat{i}$ lands at [2, 0] and $\hat{j}$ lands at [0, 1.5]. Where does $\vec{v}$ land? 

Answer: $\vec{v}$ lands at [2. 3.]

In [24]:
from numpy import array

v = array([1,2])

i_hat = array([2, 0])
j_hat = array([0, 1.5])

# fix this line
basis = array([i_hat, j_hat])

# transform vector v into w
w = basis.dot(v)

print(w) # [2. 3.]


[2. 3.]


2. Vector $\vec{v}$ has a value of [1, 2] but then a transformation happens. $\hat{i}$ lands at [-2, 1] and $\hat{j}$ lands at [1, -2]. Where does $\vec{v}$ land?

Answer: $\vec{v}$ lands at [ 0, -3]

In [25]:
from numpy import array

v = array([1,2])

i_hat = array([-2, 1])
j_hat = array([1, -2])

# fix this line
basis = array([i_hat, j_hat])

# transform vector v into w
w = basis.dot(v)

print(w) # [ 0 -3]

[ 0 -3]


3. A transformation $\hat{i}$ lands at [1, 0] and $\hat{j}$ lands at [2, 2]. What is the determinant of this transformation?

Answer:
The determinant of this transformation 2.

In [18]:
from numpy.linalg import det
from numpy import array

i_hat = array([1, 0])
j_hat = array([2, 2])

basis = array([i_hat, j_hat]).transpose()

print('Basis:\n',basis)

determinant = det(basis)

print('\nDeterminant:', determinant)  # prints 1.0

Basis:
 [[1 2]
 [0 2]]

Determinant: 2.0


4. Can two or more linear transformations be done in single linear transformation? Why or why not?

Answer:
Yes, because matrix multiplication allows us to combine several matrices into a single matrix representing one consolidated transformation.


5. Solve the system of equations for x, y, and z:

$$3x+1y+0z=54$$
$$2x+4y+1z=12$$
$$3x+1y+8z=6$$

Answer:

In [28]:
from numpy import array
from numpy.linalg import inv

# 3x+1y+0z=54
# 2x+4y+1z=12
# 3x+1y+8z=6

A = array([
    [3, 1, 0],
    [2, 4, 1],
    [3, 1, 8]
])

B = array([
    54,
    12,
    6
])

X = inv(A).dot(B)

print(X) # [19.8 -5.4 -6. ]

[19.8 -5.4 -6. ]


6. Is the following matrix linearly dependent? Why or why not?

$$
	\begin{bmatrix} 
	2 & 1 \\
	6 & 3 \\
	\end{bmatrix}
	\quad
	$$

Answer: Yes the above matrix is linearly dependent because its determinate is zero.

In [31]:
# Using Numpy
from numpy.linalg import det
from numpy import array

i_hat = array([2, 6])
j_hat = array([1, 3])

basis = array([i_hat, j_hat]).transpose()

print('Basis:\n',basis)

determinant = det(basis)

print('\nDeterminant:', determinant) # prints 0.0

Basis:
 [[2 1]
 [6 3]]

Determinant: 0.0


In [33]:
# Using Sympy
from sympy import *

basis = Matrix([
    [2,1],
    [6,3]
])

determinant = det(basis)

print('\nDeterminant:', determinant) # prints 0.0


Determinant: 0
